### ISSUE TITLE
签到用不了了·····

### ISSUE THREAD

**Issue by yanyudalao** [dandnaloveU/SignBox#4]
从 8 月 4 日开始················

**Comment by xifeng0** [comment]
是的，从4号后就无法签到了

**Comment by dandnaloveU** [comment]
已修复

**Comment by xifeng0** [comment]
> 已修复

我重新拉了下库，然后去米游社重新获取了cookie。依旧
![image](https://user-images.githubusercontent.com/76558682/184521103-049bd886-e6e7-462d-b31c-05e166faf15c.png)
